// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHQ6NYVOnNoaf0XITppusi0UFHZ8rC69U',
    appId: '1:967650947259:web:10dc64c884bcd79c62f99e',
    messagingSenderId: '967650947259',
    projectId: 'newsfeedapp-ec17a',
    authDomain: 'newsfeedapp-ec17a.firebaseapp.com',
    storageBucket: 'newsfeedapp-ec17a.appspot.com',
    measurementId: 'G-FNYN09636J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5RuqwN4ZcgtCq6svm4e1pxh_YcxcQxVI',
    appId: '1:967650947259:android:8fc2b25d0c921ab862f99e',
    messagingSenderId: '967650947259',
    projectId: 'newsfeedapp-ec17a',
    storageBucket: 'newsfeedapp-ec17a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBJyfEw1MM0_MobNtr7HoY5UxrNlIlMIA',
    appId: '1:967650947259:ios:d5c3864c1318967562f99e',
    messagingSenderId: '967650947259',
    projectId: 'newsfeedapp-ec17a',
    storageBucket: 'newsfeedapp-ec17a.appspot.com',
    iosBundleId: 'com.example.newsapp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBJyfEw1MM0_MobNtr7HoY5UxrNlIlMIA',
    appId: '1:967650947259:ios:d5c3864c1318967562f99e',
    messagingSenderId: '967650947259',
    projectId: 'newsfeedapp-ec17a',
    storageBucket: 'newsfeedapp-ec17a.appspot.com',
    iosBundleId: 'com.example.newsapp2',
  );
}
